name: Build and Run Tests

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    timeout-minutes: 15
    permissions:
      actions: write
      checks: write
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Ensure CMake is installed
      run: |
        apt-get update
        apt-get install -y cmake

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build Project
      run: cmake --build build

    - name: Run Tests
      run: cd build && ctest --output-on-failure
      continue-on-error: true

    - name: Autograding
      uses: education/autograding@v1